version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:@localhost:3306/bet
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: bet
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
