name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to server
        uses: appleboy/scp-action@v0.2.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "."
          target: "/path/to/deploy"

      - name: Restart Docker containers
        run: |
          ssh -i ${{ secrets.VPS_KEY }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
          "cd /path/to/deploy && docker-compose up --build -d"
